package.json
src/donationComponents/DonationPage.tsx
src/donationComponents/components/DonationForm.tsx
src/donationComponents/components/NonAuthDonation.tsx
src/donationComponents/components/NonAuthDonationInner.tsx

https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/193

pass appearance as props to donation forms for 0.0.7

---

package.json
src/components/FormSubmissionEdit.tsx
src/donationComponents/components/NonAuthDonationInner.tsx

https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/194

add cover fees option to logged out donation form for 0.0.8

---

package.json
src/components/ExportLink.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/207

export dates in people.csv

---

package.json
src/components/ImageEditor.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/203

fix: snap the cropbox to the image

---

package-lock.json
package.json
src/components/FormSubmissionEdit.tsx
src/components/QuestionEdit.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/225

improve: add country support to phone field

---

package.json
src/components/gallery/GalleryModal.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/232

0.1.9 - allow deleting images from the gallery

---

package-lock.json
package.json
src/components/ExportLink.tsx
src/components/reporting/ReportOutput.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/246

add: person based report to donation summary

---

package-lock.json
package.json
src/components/markdownEditor/editor.css
src/components/markdownEditor/plugins/ToolbarPlugin.tsx
src/components/markdownEditor/plugins/customLink/FloatingLinkEditor.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/250

fix: markdown editor menus

---

package-lock.json
package.json
src/helpers/AppearanceHelper.ts

https://github.com/ChurchApps/ChurchAppsSupport/issues/248

add: ogImage to appearance helper

---

package-lock.json
package.json
src/components/wrapper/UserMenu.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/256

0.2.15 - make church list scrollable in church menu

---

package-lock.json
package.json
src/components/QuestionEdit.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/261

feat: add checkbox option in forms

---

package-lock.json
package.json
src/components/wrapper/SiteWrapper.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/275

0.2.27-expand siteWrapper nav on hover

---

package-lock.json
package.json
src/pageComponents/components/SelectChurchModal.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/292

0.2.28 - add logout option to select church screen

---

package-lock.json
package.json
src/components/notes/Notes.tsx
src/components/wrapper/PrivateMessages.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/293

0.2.29 - switch to basic person lookup route for private messages

---

public/locales/no.json
src/donationComponents/DonationPage.tsx

Updated Norwegian strings & fixed a typo

Updated Norwegian translations

---

package-lock.json
package.json
public/locales/en.json
src/components/wrapper/ChurchList.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/279

allow users to remove themselves from a church

---

package-lock.json
package.json
public/locales/en.json
src/components/CreatePerson.tsx
src/components/PersonAdd.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/297

improve: show createPerson in modal form and add email

---

package-lock.json
package.json
src/components/QuestionEdit.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/336

0.2.36 - make form input labels bold

---

package-lock.json
package.json
src/components/markdownEditor/editor.css

https://github.com/ChurchApps/ChurchAppsSupport/issues/353

fix: text editor heading/link options menu

---

package-lock.json
package.json
src/components/markdownEditor/plugins/ToolbarPlugin.tsx
src/components/markdownEditor/plugins/customLink/FloatingLinkEditor.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/355

fix: link/heading options dropdown position

---

package-lock.json
package.json
src/components/FormCardPayment.tsx
src/components/FormSubmissionEdit.tsx
src/components/QuestionEdit.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/300

feat: add payment field to forms

---

package-lock.json
package.json
src/components/reporting/ReportOutput.tsx
src/components/reporting/ReportWithFilter.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/397

improve: report output icons

---

src/donationComponents/components/NonAuthDonationInner.tsx

Fixed the regex to allow for a variety of different email endings than just .com or .net

Email Validation Fix

---

package-lock.json
package.json
src/components/header/SiteHeader.tsx
src/components/header/SupportDrawer.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/439

improve: support modal

---

package-lock.json
package.json
src/components/notes/AddNote.tsx
src/components/notes/Conversation.tsx
src/components/notes/Note.tsx
src/components/notes/Notes.tsx
src/components/wrapper/UserMenu.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/510

improve: only allow the sender to edit the message

---

package-lock.json
package.json
src/components/FormCardPayment.tsx
src/components/FormSubmissionEdit.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/525

add: user name to payment successfull string

---

package-lock.json
package.json
src/components/markdownEditor/Editor.tsx
src/components/markdownEditor/MarkdownPreview.tsx
src/components/markdownEditor/MarkdownPreviewLight.tsx
src/components/markdownEditor/plugins/FloatingTextMenu/FloatingTextFormatToolbarPlugin.tsx
src/components/markdownEditor/plugins/FloatingTextMenu/getDOMRangeRect.tsx
src/components/markdownEditor/plugins/FloatingTextMenu/getSelectNode.tsx
src/components/markdownEditor/plugins/FloatingTextMenu/setFloatingElemPosition.tsx
src/components/markdownEditor/plugins/MarkdownTransformers.ts

https://github.com/ChurchApps/ChurchAppsSupport/issues/437

add: floating text format toolbar

---

package-lock.json
package.json
src/components/markdownEditor/plugins/customLink/FloatingLinkEditor.tsx
src/components/markdownEditor/plugins/emoji/EmojisPlugin.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/535

fix: link editor position

---

package-lock.json
package.json
src/donationComponents/components/DonationForm.tsx
src/donationComponents/components/NonAuthDonationInner.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/433

get transaction fee from /donate/fee

---

package-lock.json
package.json
src/components/reporting/ReportOutput.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/502

improve: group attendance download report

---

package-lock.json
package.json
src/components/wrapper/Notifications.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/526

add: view details button to notifications

---

package-lock.json
package.json
src/donationComponents/components/FundDonation.tsx
src/donationComponents/components/NonAuthDonationInner.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/438

improve: switch from amounts to amount for fund donations search params

---

package-lock.json
package.json
src/components/FormSubmissionEdit.tsx

https://github.com/ChurchApps/ChurchAppsSupport/issues/560

improve: avoid double click on form submission
